all: wordsearch.exe wordgen.exe pager.exe launcher.exe

wordsearch.exe: wordsearch.c
	gcc -o wordsearch wordsearch.c

wordgen.exe: wordgen.c
	gcc -o wordgen wordgen.c

pager.exe: pager.c
	gcc -o pager pager.c

launcher.exe: launcher.c
	gcc -o launcher launcher.c
